language: node_js
node_js: stable

cache:
  directories:
    - node_modules

git:
  depth: 1
  quiet: true

branches:
  only:
  - master

pre_install:
  - npm i yarn
install:
  - yarn

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "zombie110year"
  - git config user.email "zombie110year@outlook.com"
  - git add .
  - git commit -m "update blog"
  - git push --force --quiet "https://${github_token}@${github_url}" master:master


env:
  global:
    - github_url: github.com/zombie110year/zombie110year.github.io.git
